[2022-02-08 16:26:39,922] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: gcs_to_bq_dag.gcs_2_gcs_task scheduled__2022-02-07T00:00:00+00:00 [queued]>
[2022-02-08 16:26:39,934] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: gcs_to_bq_dag.gcs_2_gcs_task scheduled__2022-02-07T00:00:00+00:00 [queued]>
[2022-02-08 16:26:39,935] {taskinstance.py:1238} INFO - 
--------------------------------------------------------------------------------
[2022-02-08 16:26:39,936] {taskinstance.py:1239} INFO - Starting attempt 13 of 13
[2022-02-08 16:26:39,936] {taskinstance.py:1240} INFO - 
--------------------------------------------------------------------------------
[2022-02-08 16:26:39,949] {taskinstance.py:1259} INFO - Executing <Task(GCSToGCSOperator): gcs_2_gcs_task> on 2022-02-07 00:00:00+00:00
[2022-02-08 16:26:39,955] {standard_task_runner.py:52} INFO - Started process 19622 to run task
[2022-02-08 16:26:39,960] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'gcs_to_bq_dag', 'gcs_2_gcs_task', 'scheduled__2022-02-07T00:00:00+00:00', '--job-id', '721', '--raw', '--subdir', 'DAGS_FOLDER/gcs_2_bq_dag.py', '--cfg-path', '/tmp/tmp9t32qgz4', '--error-file', '/tmp/tmpmii1jk0y']
[2022-02-08 16:26:39,961] {standard_task_runner.py:77} INFO - Job 721: Subtask gcs_2_gcs_task
[2022-02-08 16:26:40,031] {logging_mixin.py:109} INFO - Running <TaskInstance: gcs_to_bq_dag.gcs_2_gcs_task scheduled__2022-02-07T00:00:00+00:00 [running]> on host 28fada1679c0
[2022-02-08 16:26:40,093] {taskinstance.py:1426} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=gcs_to_bq_dag
AIRFLOW_CTX_TASK_ID=gcs_2_gcs_task
AIRFLOW_CTX_EXECUTION_DATE=2022-02-07T00:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-02-07T00:00:00+00:00
[2022-02-08 16:26:40,096] {crypto.py:82} WARNING - empty cryptography key - values will not be stored encrypted.
[2022-02-08 16:26:40,097] {gcs_to_gcs.py:346} INFO - Delimiter ignored because wildcard is in prefix
[2022-02-08 16:26:40,469] {taskinstance.py:1700} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1329, in _run_raw_task
    self._execute_task_with_callbacks(context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1455, in _execute_task_with_callbacks
    result = self._execute_task(context, self.task)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1511, in _execute_task
    result = execute_callable(context=context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/google/cloud/transfers/gcs_to_gcs.py", line 274, in execute
    self._copy_source_with_wildcard(hook=hook, prefix=prefix)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/google/cloud/transfers/gcs_to_gcs.py", line 348, in _copy_source_with_wildcard
    objects = hook.list(self.source_bucket, prefix=prefix_, delimiter=delimiter)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/google/cloud/hooks/gcs.py", line 699, in list
    for blob in blobs:
  File "/home/airflow/.local/lib/python3.7/site-packages/google/api_core/page_iterator.py", line 214, in _items_iter
    for page in self._page_iter(increment=False):
  File "/home/airflow/.local/lib/python3.7/site-packages/google/api_core/page_iterator.py", line 253, in _page_iter
    page = self._next_page()
  File "/home/airflow/.local/lib/python3.7/site-packages/google/api_core/page_iterator.py", line 382, in _next_page
    response = self._get_next_page_response()
  File "/home/airflow/.local/lib/python3.7/site-packages/google/api_core/page_iterator.py", line 442, in _get_next_page_response
    method=self._HTTP_METHOD, path=self.path, query_params=params
  File "/home/airflow/.local/lib/python3.7/site-packages/google/cloud/storage/_http.py", line 80, in api_request
    return call()
  File "/home/airflow/.local/lib/python3.7/site-packages/google/api_core/retry.py", line 291, in retry_wrapped_func
    on_error=on_error,
  File "/home/airflow/.local/lib/python3.7/site-packages/google/api_core/retry.py", line 189, in retry_target
    return target()
  File "/home/airflow/.local/lib/python3.7/site-packages/google/cloud/_http.py", line 484, in api_request
    raise exceptions.from_http_response(response)
google.api_core.exceptions.Forbidden: 403 GET https://storage.googleapis.com/storage/v1/b/dtc_data_lake_pivotal-surfer-336713/o?projection=noAcl&prefix=raw%2Fyellow_tripdata_&delimiter=.parquet&prettyPrint=false: airflow@rational-aria-338717.iam.gserviceaccount.com does not have storage.objects.list access to the Google Cloud Storage bucket.
[2022-02-08 16:26:40,494] {taskinstance.py:1277} INFO - Marking task as FAILED. dag_id=gcs_to_bq_dag, task_id=gcs_2_gcs_task, execution_date=20220207T000000, start_date=20220208T162639, end_date=20220208T162640
[2022-02-08 16:26:40,509] {standard_task_runner.py:92} ERROR - Failed to execute job 721 for task gcs_2_gcs_task
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/task/task_runner/standard_task_runner.py", line 85, in _start_by_fork
    args.func(args, dag=self.dag)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/cli/cli_parser.py", line 48, in command
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/cli.py", line 92, in wrapper
    return f(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/cli/commands/task_command.py", line 298, in task_run
    _run_task_by_selected_method(args, dag, ti)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/cli/commands/task_command.py", line 107, in _run_task_by_selected_method
    _run_raw_task(args, ti)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/cli/commands/task_command.py", line 184, in _run_raw_task
    error_file=args.error_file,
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/session.py", line 70, in wrapper
    return func(*args, session=session, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1329, in _run_raw_task
    self._execute_task_with_callbacks(context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1455, in _execute_task_with_callbacks
    result = self._execute_task(context, self.task)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1511, in _execute_task
    result = execute_callable(context=context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/google/cloud/transfers/gcs_to_gcs.py", line 274, in execute
    self._copy_source_with_wildcard(hook=hook, prefix=prefix)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/google/cloud/transfers/gcs_to_gcs.py", line 348, in _copy_source_with_wildcard
    objects = hook.list(self.source_bucket, prefix=prefix_, delimiter=delimiter)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/google/cloud/hooks/gcs.py", line 699, in list
    for blob in blobs:
  File "/home/airflow/.local/lib/python3.7/site-packages/google/api_core/page_iterator.py", line 214, in _items_iter
    for page in self._page_iter(increment=False):
  File "/home/airflow/.local/lib/python3.7/site-packages/google/api_core/page_iterator.py", line 253, in _page_iter
    page = self._next_page()
  File "/home/airflow/.local/lib/python3.7/site-packages/google/api_core/page_iterator.py", line 382, in _next_page
    response = self._get_next_page_response()
  File "/home/airflow/.local/lib/python3.7/site-packages/google/api_core/page_iterator.py", line 442, in _get_next_page_response
    method=self._HTTP_METHOD, path=self.path, query_params=params
  File "/home/airflow/.local/lib/python3.7/site-packages/google/cloud/storage/_http.py", line 80, in api_request
    return call()
  File "/home/airflow/.local/lib/python3.7/site-packages/google/api_core/retry.py", line 291, in retry_wrapped_func
    on_error=on_error,
  File "/home/airflow/.local/lib/python3.7/site-packages/google/api_core/retry.py", line 189, in retry_target
    return target()
  File "/home/airflow/.local/lib/python3.7/site-packages/google/cloud/_http.py", line 484, in api_request
    raise exceptions.from_http_response(response)
google.api_core.exceptions.Forbidden: 403 GET https://storage.googleapis.com/storage/v1/b/dtc_data_lake_pivotal-surfer-336713/o?projection=noAcl&prefix=raw%2Fyellow_tripdata_&delimiter=.parquet&prettyPrint=false: airflow@rational-aria-338717.iam.gserviceaccount.com does not have storage.objects.list access to the Google Cloud Storage bucket.
[2022-02-08 16:26:40,544] {local_task_job.py:154} INFO - Task exited with return code 1
[2022-02-08 16:26:40,578] {local_task_job.py:264} INFO - 0 downstream tasks scheduled from follow-on schedule check
